# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Olis.dev
dev_addr: localhost:8001
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/olis-logo-t.png
  palette:
    scheme: olis
extra_css:
  - stylesheets/olis.css
markdown_extensions:
  - admonition
  - attr_list
use_directory_urls: true
nav:
  - 'index.md'
  - API: 'api.md'
  - Ontology: 'ont.md'
  - Ont RDF: 'assets/olis.ttl'
plugins:
  - redirects:
      redirect_maps:
        'ontrdf.md': 'https://github.com/Kurrawong/olis.dev/raw/master/docs/assets/olis.ttl'