[project]
name = "olis.dev"
version = "0.1.0"
description = "The content of the website https://olis.dev"
authors = [{ name = "Nicholas Car", email = "nick@kurrawong.ai" }]
requires-python = ">=3.12,<4"
dependencies = [
    "mkdocs-material>=8.3.9,<9",
    "mkdocs-redirects>=1.2.1,<2",
]

[dependency-groups]
dev = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["docs"]